imagestore/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.urls import re_path
from .views import AlbumListView, ImageListView, UpdateImage, UpdateAlbum, \
    CreateImage, CreateAlbum, DeleteImage, DeleteAlbum, ImageView, \
    ImageTagAutocompleteView

app_name = 'imagestore'

urlpatterns = [
    re_path(r'^$', AlbumListView.as_view(), name='index'),

    re_path(r'^album/add/$', CreateAlbum.as_view(), name='create-album'),
    re_path(r'^album/(?P<album_id>\d+)/$', ImageListView.as_view(), name='album'),
    re_path(r'^album/(?P<pk>\d+)/edit/$', UpdateAlbum.as_view(), name='update-album'),
    re_path(r'^album/(?P<pk>\d+)/delete/$', DeleteAlbum.as_view(), name='delete-album'),

    re_path(r'^tag/(?P<tag>[^/]+)/$', ImageListView.as_view(), name='tag'),

    re_path(r'^user/(?P<username>\w+)/albums/', AlbumListView.as_view(), name='user'),
    re_path(r'^user/(?P<username>\w+)/$', ImageListView.as_view(), name='user-images'),

    re_path(r'^upload/$', CreateImage.as_view(), name='upload'),

    re_path(r'^image/(?P<pk>\d+)/$', ImageView.as_view(), name='image'),
    re_path(r'^album/(?P<album_id>\d+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-album'),
    re_path(r'^tag/(?P<tag>[^/]+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-tag'),
    re_path(r'^image/(?P<pk>\d+)/delete/$', DeleteImage.as_view(), name='delete-image'),
    re_path(r'^image/(?P<pk>\d+)/update/$', UpdateImage.as_view(), name='update-image'),

    re_path(r'^tag-autocomplete/$', ImageTagAutocompleteView.as_view(), name='tag-autocomplete'),
]

imagestore/models/image.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import swapper
from django.utils.translation import gettext_lazy as _
from .bases.image import BaseImage


class Image(BaseImage):
    class Meta(BaseImage.Meta):
        abstract = False
        app_label = 'imagestore'
        verbose_name = _('Image')
        verbose_name_plural = _('Images')
        swappable = swapper.swappable_setting('imagestore', 'Image')

imagestore/templates/imagestore/album_delete.html
{% extends "imagestore/base.html" %}

{% load i18n %}

{% block content %}
    <p>{% trans "Are you sure that you would like to delete this album?" %}</p>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock %}

imagestore/templates/imagestore/album_list.html
{% extends "imagestore/base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load voting_tags %}
{% load hitcount_tags %}
{% load comment_tags %}
{% load userProfile_tags %}
{% load inbox %}
{% load static %}

{% block extra_head %}
    <script type="text/javascript">   
    $(document).ready(function() {
            {% for album in album_list %}
                {% get_hit_count_javascript for album %}
            {% endfor %}
    });
    </script>
{% endblock %}



{% block title %}
    {% if view_user %}
        {% trans "Albums for user" %} {{ view_user }}
    {% else %}
        {% trans "All albums" %}
    {% endif %}
{% endblock %}

{% block imagestore-breadcrumb %}
    <li>
        {% if view_user %}
            {% trans "Albums for user" %} {{ view_user }}
        {% else %}
            {% trans "All albums" %}
        {% endif %}
    </li>
{% endblock %}

{% block imagestore-info %}
    {% if view_user and IMAGESTORE_SHOW_USER %}
        {% with user=view_user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}
{% endblock %}

{% block imagestore-related %}
    {% include "imagestore/tag-cloud.html" %}
{% endblock %}

{% block content %}
    {% get_owned_blog view_user as blog %}
    <h6 class="noGutter">
    {% if view_user == user %}
        {% trans "Uploaded Images " %} {{ blog.num_images }} {% trans "/" %} {{ max_images }}
    {% else %}
    {% endif %}
    </h6>
    {% if album_list|length == 0%}
        <h6 class="noGutter">
        {% if view_user == user %}
        {% get_owned_blog view_user as blog %}
            {% trans "Upload Photos to showcase you collection to potential customers." %}
        {% else %}
            {{blog.title|title}} {% trans "has not uploaded any Photos." %}
        {% endif %}
        </h6>
    {% else %}
        {% include "imagestore/pagination.html" %}
        <div class='album-list'>
            {% for album in album_list %}
                <div class='album pagination-centered bottomHalfGutter {% if not forloop.first %}halfGutter{% endif %}'>
                    <div class='album-head'>
                        <!--a class="album_photos" href="{{ album.get_absolute_url }}"-->
                        {% if album.get_head %}
                            <a class="album_photos album_photos_ex" href="{% url imagestore:render_album album.id %}">
                                {% thumbnail album.get_head.image "100x100" crop='center' as album_head %}
                                    <img {% if album.name %} alt="{{ album.name }}" {% endif %} src="{{ album_head.url }}">
                                {% endthumbnail %}
                                <div class="album-name colorBlack fontTitillium1 fontSize13 topHalfGutter">{{ album.name }}</div>
                            </a>
                            {% include 'generic/includes/render_voting.html' with object=album %}

                            <span>{% trans "Views&nbsp;" %}({% get_hit_count for album %})</span>

                        {% else %}
                            <a class="album_photos album_photos_ex" href="{% url imagestore:render_album album.id %}">
                                <img src="{% static 'img/emptyAlbum.png' %}">
                                <div class="album-name colorBlack fontTitillium1 fontSize13 topHalfGutter">{{ album.name }}</div>
                            </a>
                        {% endif %}
                        {% if album.user == request.user and request.user.is_authenticated %}
                            <a class="delete_album" href="{% url imagestore:delete-album album.id %}">{% trans "Delete Album" %}</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
        {% include "imagestore/pagination.html" %}
    {% endif %}
{% endblock %}

imagestore/templates/imagestore/base.html
{% extends IMAGESTORE_TEMPLATE|default:"base.html" %}
{% load i18n %}
{% load static %}

{% block head %}
    {% if IMAGESTORE_LOAD_CSS %}
        <link rel="stylesheet" type="text/css" href="{% static 'imagestore/imagestore.css' %}" media="screen" />
    {% endif %}
{% endblock %}

{% block breadcrumb %}
    <ul class='breadcrumb'>
        {% if request.path != '/' %}
            <li><a href="/">{% trans "Home" %}</a> <span class="divider">/</span></li>
        {% endif %}
        {% if request.path != imagestore_index_url %}
            <li><a href="{{ imagestore_index_url }}">{% trans "Gallery" %}</a> <span class="divider">/</span></li>
        {% endif %}
        {% block imagestore-breadcrumb %}
    {% endblock %}
    </ul>
{% endblock %}

{% block content %}
{% endblock content %}

{% block content-related %}
        {% block imagestore-info %}
        {% endblock %}
        <div id="controls">
            <ul>
                {% if imagestore_perms.add_image or request.user.is_superuser %}
                    <li><a href={% url 'imagestore:upload' %}>{% trans "Upload image" %}</a></li>
                {% endif %}
                {% if imagestore_perms.add_album or request.user.is_superuser %}
                    <li><a href={% url 'imagestore:create-album' %}>{% trans "Create new album" %}</a></li>
                {% endif %}
                {% block controls %}
                {% endblock controls %}
            </ul>
        </div>
        {% block imagestore-related %}
        {% endblock %}
{% endblock %}

imagestore/templates/imagestore/image-scope.html
{% load i18n %}
{% if view_user %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-view-user'>{% endif %}
        {% trans "User" %}: {{ view_user }}
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}
{% if album %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-album'>{% endif %}
		<span class="album_name"> {{ album.name }}</span> <!-- class album_name = 'album_' + Field Name -->
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}
{% if tag %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-album'>{% endif %}
    {% trans "Tag" %}: {{ tag }}
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}

imagestore/templates/imagestore/image.html
{% extends "imagestore/base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load tagging_tags %}

{% block title %}
    {% trans "Image" %} - {{ image.title }}
{% endblock %}

{% block imagestore-breadcrumb %}
    {% if view_user and IMAGESTORE_SHOW_USER %}
        <li class='scope-view-user'><a href="{% url 'imagestore:user-images' username=view_user %}">{% trans "User" %}: {{ view_user }}</a> <span class="divider">/</span></li>
    {% endif %}
    {% if album %}
        <li class='scope-album'><a href="{{ album.get_absolute_url }}">{% trans "Album" %}: {{ album.name }}</a> <span class="divider">/</span></li>
    {% endif %}
    {% if tag %}
        <li class='scope-tag'><a href="{% url 'imagestore:tag' tag=tag %}">{% trans "Tag" %}: {{ tag }}</a> <span class="divider">/</span></li>
    {% endif %}
    <li>
        {% if image.title %}
            {{ image.title }}
        {% else %}
            {{ image.id }}
        {% endif %}
    </li>
{% endblock %}

{% block imagestore-info %}
    <div class='user-info'>
    {% if IMAGESTORE_SHOW_USER %}
        {% with user=image.user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}
    </div>
{% endblock %}

{% block content %}
        {% if image.title %}<h1>{{ image.title }}</h1>{% endif %}
        {% if album or tag or view_user %}
            <h2>
                    {% include "imagestore/image-scope.html" %}
            </h2>
        {% endif %}
        <div class="image-description">
            {{ image.description }}
        </div>
        <div id="image-view">
            <div class="navigation">
                {% if previous %} <a class="previous-link" href="
                {% with previous as image %}
                    {% include "imagestore/image-href.html" %}
                {% endwith %}
                ">← {% trans "previous image" %}</a> {% endif %}
                {% if next %} <a class="next-link" href="{% with next as image %}
                    {% include "imagestore/image-href.html" %}
                {% endwith %}">{% trans "next image" %} →</a> {% endif %}
            </div>
            {% thumbnail image.image "800x800" as full_im %}
                <img class="preview" {% if image.title %} alt="{{ image.title }}" {% endif %} src="{{ full_im.url }}">
            {% endthumbnail %}
        </div>
{% endblock content %}

{% block controls %}
    {% if request.user == image.user or perms.imagestore.moderate_images %}
        <li><a href="{% url 'imagestore:update-image' image.id %}">{% trans "Edit info" %}</a></li>
        <li><a href="{% url 'imagestore:delete-image' image.id %}">{% trans "Delete image" %}</a></li>
    {% endif %}
{% endblock %}

{% block imagestore-related %}

     <div class="tagging">
            <h2>{% trans "Tags" %}</h2>
            {% tags_for_object image as itags %}
            {% for tag in itags %}
                <a href="{% url 'imagestore:tag' tag.name %}">{{ tag.name }}</a>
            {% endfor %}
     </div>
     {% if image.place %}
         <div class='place'>
            <h2>{% trans "Place" %}</h2>
            <a href="{{ image.place.get_absolute_url }}">{{ image.place.name }} →</a>
         </div>
     {% endif %}
{% endblock %}

imagestore/templates/imagestore/image_confirm_delete.html
{% extends "imagestore/base.html" %}

{% load i18n %}

{% block content %}
    <p>{% trans "Are you sure that you would like to delete this image?" %}</p>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock %}

imagestore/templates/imagestore/image_delete.html
{% extends "imagestore/base.html" %}

{% load i18n %}

{% block content %}
    <p>{% trans "Are you sure that you would like to delete this image?" %}</p>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock %}

imagestore/templates/imagestore/image_list.html
{% extends "imagestore/base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load imagestore_tags %}

{% block imagestore-breadcrumb %}
    {% with "li" as scope_tag %}
        {% include "imagestore/image-scope.html" %}
    {% endwith %}
{% endblock %}

{% block title %}
    {% include "imagestore/image-scope.html" %}
{% endblock %}

{% block imagestore-info %}
    {% if view_user and IMAGESTORE_SHOW_USER %}
        {% with user=view_user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}
    {% if album and IMAGESTORE_SHOW_USER %}
        {% with user=album.user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}

{% endblock %}


{% block controls %}
    {% if album %}
        {% if request.user == album.user or perms.imagestore.moderate_albums %}
            <li><a href='{% url 'imagestore:update-album' pk=album.pk %}'>{% trans "Edit album" %}</a></li>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    <h1>
        {% include "imagestore/image-scope.html" %}
    </h1>
    {% include "imagestore/pagination.html" %}
    <div id="image-thumbnails">
        {% for image in image_list %}
            <div class='image-preview'>
            {% thumbnail image.image "120x120" crop="center" as im %}
                <a class="thumb" rel='gallery-image[ilist]' href="{{ image.image.url }}">
                    <img class="preview" {% imagestore_alt image forloop.counter %} src="{{ im.url }}">
                </a>
                <a href="{% include "imagestore/image-href.html" %}">
                    {% if image.title %}
                        <br><span class='image-title'>{{ image.title }}</span>
                    {% else %}
                        {% trans 'Info' %}
                    {% endif %}
                </a>
            {% endthumbnail %}
            </div>
        {% endfor %}
    </div>
    {% include "imagestore/pagination.html" %}
{% endblock %}

imagestore/templates/imagestore/pphoto.html
{% load static %}

<link rel="stylesheet" href="{% static 'prettyphoto/css/prettyPhoto.css' %}" type="text/css" media="screen" charset="utf-8" />
<script src="{% static 'prettyphoto/js/jquery.prettyPhoto.js' %}" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript" charset="utf-8">
    var prettyparams = {
        animation_speed: 'fast',
        slideshow: 3000,
        autoplay_slideshow: false,
        opacity: 0.7,
        show_title: true,
        allow_resize: true,
        default_width: 1000,
        default_height: 344,
        counter_separator_label: '/',
        theme: 'facebook',
        overlay_gallery: true,
        changepicturecallback: function() {$pp_overlay.css({'height':$(document).height()})},
        };
    $(function(){$("a[rel^='gallery-image']").prettyPhoto(prettyparams)});
</script>

imagestore/templates/imagestore/render_image_ex_list.html
{% load i18n %}
{% load thumbnail %}
{% load url from future %}
{% load static %}
{% load userProfile_tags %}

{% block content %}
        {% for image in image_list %}
        	{% get_reldata_url image as rel_data_url %} 
            {% if image.id != exclude_id %}
                {% thumbnail image.image "120x120" crop="center" as im %}
                    <a class="album_in_feed" rel='gallery-image[ilist]' href="{{ image.image.url }}" data-reldata-url="{{rel_data_url}}"></a>
                {% endthumbnail %}
            {% endif %}
        {% endfor %}
{% endblock %}

imagestore/templates/imagestore/render_image_list.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load voting_tags %}
{% load comment_tags %}
{% load url from future %}
{% load inbox %}
{% load userProfile_tags %}
{% load static %}
{% load imagestore_tags %}

{% block extra_css %}
<link rel="stylesheet" href="{% static "css/albumpage.css" %}"/>
{% endblock %}

{% block extra_js %}
<script src="{% static "js/jquery.sortable.js" %}"></script>
<script src="{% static "js/comment.handlers.js" %}"></script>

<script type="text/javascript">
    var image_order_array = [];
    var startIndex = 0;
    $(document).ready(function() {
        var $children = $('#image-thumbnails').children();
        $children.each(function(idx, itm) {
            image_order_array.push($(itm).attr('data-order'));
        });
        $('a.album-image').fancybox({
                        scrolling: 'yes',
                        minWidth:500,
                        minHeight:450,
                        autoSize: true,
                        helpers : { overlay : { locked : false } }
                      });
        $('.upload_album').on('click', function(event){
            $('#id_image').click();
            return false;
        });
        $('.edit_album').on('click', function(event){
            $('.edit_album_form').show();
            $('.update-album').on('submit', edit_album_form_submit_handler);
            return false;
        });
       $("#id_image").change(function() {
            $('.upload-image').submit();
            return false;
        });
        install_comment_on_object_handler();
        {% if request.user == album.user or perms.imagestore.moderate_albums %}
        {% if request.user.is_authenticated  %}

        $('.sortable').sortable().bind('dragstart.h5s', function(event){
            startIndex = $(event.target).parents('.image-preview').index();
        }).bind('sortupdate', function(event, data) {
                var $element_dragged = data.item;
                if($element_dragged) {
                    var prev_order = $element_dragged.data("order");
                    var new_order;

                    if($element_dragged.index() > startIndex) {
                        new_order = $element_dragged.prev().attr('data-order');
                    } else {
                        new_order = $element_dragged.next().attr('data-order');
                    }

                    var image_id    = $element_dragged.data("id");
                    var link        = "{% url 'imagestore:update-album-order' 0 0  %}" ;

                    var linksplit                   = link.split("/");
                    linksplit[linksplit.length-2]   = new_order;
                    linksplit[linksplit.length-3]   = image_id;
                    link                            = linksplit.join('/');
                    
                    $.get(link, {}, function(data) {
                        var ret_data = JSON.parse(data);
                        if(ret_data.success) {
                            var $children = $element_dragged.parent().children();
                            $children.each(function(idx, itm) {
                                $(itm).attr('data-order', image_order_array[idx]);
                            });
                            console.log("Album is rearranged successfully!!");
                        }
                        else
                            console.log("Album rearrangement Failed!!");
                    });
                }
            });
    		var edit_image_submit_handler = function(){
    		        var $form = $(this);
    		        $.ajax({
    		            type: $form.attr('method'),
    		            url: $form.attr('action'),
    		            data: $form.serialize(),
    		            success: function (data) {
    		                var ret_data = data;
    		                if(ret_data.success) {
    		                	alert("updated successfully!!");
    		                	$.fancybox.close();
    		                } else {
    			                var errors = ret_data.errors;
    		                    $('.fancybox-inner').find('.error').removeClass('error');
    		                    $.each( errors, function( key, value ) {
    		                        $('.fancybox-inner').find('[name="' + key + '"]').addClass('error');
    		                    });
    		                }

    		            },
    		            error: function(data) {
    		            	console.log(data);
    		            }
    		        });
    		    return false;
    		};
            $('.editImage').click(function(event){
                var $url = $(this).attr("href");
                var afterShowCallback = function() {
                                            var $editImageFormContainer = $('.fancybox-inner').find('.edit-image');
                                            $editImageFormContainer.submit(edit_image_submit_handler);
                                        };

                doOpenUrlWithAjaxFancyBox($url, afterShowCallback);

    		    event.stopPropagation();
    		    event.preventDefault();
    		    return false;
            });

	        var onDelete = function(){
	        	var $element = $(this);
                $.confirm({
                    text: "Are you sure you want to delete this photo?",
                    confirm: function(button) {
                    $.ajax({
                      type: "POST",
                      url: $element.attr('href'),
                      success: function(data){
                            if(data.success === true) {
                                var $container = $element.parents('.image-preview');
                                $container.remove();
                            }
                      },
                      error: function(XMLHttpRequest, textStatus, errorThrown) {
                         console.log("error during image deletion");
                      }
                    });
                    },
                    cancel: function(button) {
                        // do something
                    }
                });
				return false;
	        }

	        $(".deleteImage").click(onDelete);

        {% endif %}
        {% endif %}
    });
</script>
<style>


        .sortable.grid {
            overflow: hidden;
        }
        .sortable li {
            list-style: none;
            color: #1C94C4;
            margin: 5px;
            padding: 5px;
            float:left;
            height:120px;
            width:120px;
        }

        .handle {
            cursor: move;
        }

        li.highlight {
            background: #FEE25F;
        }
        li.sortable-placeholder {
            border: 1px dashed #CCC;
            background: none;
            margin: 5px;
            padding: 0px;
        }

</style>
{% endblock %} 


{% block main %}
{% get_owned_blog album.user as blog %}

<div class="row topHalfGutter">
    <div class="row">
        <div class="span7">
            <h6>
                <a href="{{ blog.get_absolute_url  }}">{{blog}}</a> | {% include "imagestore/image-scope.html" %}
            </h6>
        </div>
    </div>
{% block controls %}
    {% if album %}
        {% if request.user == album.user or perms.imagestore.moderate_albums %}
        {% if request.user.is_authenticated  %}
            <div class="row">
                <div class="span7">
                    <a class="upload_album albumManage fontTitillium1 fontSize13 colorWhite" href="#">{% trans "Add image" %}</a>
                    <a class="edit_album albumManage fontTitillium1 fontSize13 colorWhite" href='{% url 'imagestore:update-album' pk=album.pk %}'>{% trans "Edit album" %}</a>
                    {% render_minimal_image_upload_form album.id %}
                    <div class="edit_album_form" style="display:none">
                        {% render_minimal_album_update_form album.id %}
                    </div>
                </div>
            </div>
        {% endif %}
		{% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    {% include "imagestore/pagination.html" %}
    <div class="row">
        <div class="span7">
            <ul id="image-thumbnails" class="sortable">
                {% for image in image_list %}
                    <li class='image-preview topHalfGutter' data-id="{{image.id}}" data-order="{{image.order}}">
                    {% get_reldata_url image as rel_data_url %}
                    {% thumbnail image.image "120x120" crop="center" as im %}
                        {% if request.user == album.user or perms.imagestore.moderate_albums %}
                        {% if request.user.is_authenticated  %}
                        <span class="pull-right">
                            <a href="{% url 'imagestore:edit-image' image.id  %}" class="editImage"><img class="noBoxShadow" width="10px" height="10px" src="{% static "img/edit.png" %}"></a>
                            <a href="{% url 'imagestore:delete-image' image.id %}" class="deleteImage"><img class="noBoxShadow" width="10px" height="10px" src="{% static "img/cross_button.png" %}"></a>
                        </span>
                        {% endif %}
                        {% endif %}
                        <a class="album-image" rel='gallery-image[ilist]' href="{{ image.image.url }}" data-reldata-url="{{rel_data_url}}">
                            <img class="preview" {% if image.title %} alt="{{ image.title }}" {% endif %} src="{{ im.url }}">
                                {#% include 'imagestore/render_voting.html' with object=image %#}

                                {#% if image.title %#}
                                    <!--br><span class='image-title'>{{ image.title }}</span-->
                                {#% endif %#}                
        				</a>
        <!--                 <a href="{#% include "imagestore/image-href.html" %#}">
                            {#% if image.title %#}
                                <br><span class='image-title'>{{ image.title }}</span>
                            {#% else %#}
                                {#% trans 'Info' %#}
                            {#% endif %#}
                        </a> -->
                    {% endthumbnail %}
                    </li>
                    <!-- <a href="{#% url 'imagestore:delete-image' image.id %#}"><img src="{#% static "img/delete.png" %#}"></img></a> -->
                    {#% if image.user != request.user %#}
                        {#% include 'actstream/render_spam_report.html' with object=image %#}
                    {#% endif %#}
                {% endfor %}
            </ul>
        </div>
    </div>
        {% if album %}
            <div class="row topHalfGutter fontTitillium1 color5D fontSize12">
                <div class="span6 whiteBoxLarge subcomments_container">
                    {% include 'actstream/render_subcomments_actstream.html' with object=album %}
                </div>
            </div>
        {% endif %}
    {% include "imagestore/pagination.html" %}

{% endblock %}
</div>
{% endblock %}

imagestore/templates/imagestore/render_voting.html
{% load i18n %}
{% load voting_tags %}      
{% load userProfile_tags %}
{% load url from future %}
{% if object %}

    {% score_for_object  object as score %}
    {% voters_for_object object as voters %}

    {% vote_by_user request.user on object as vote %}
    <span>
    {% if not vote %}
        {% if object|get_class_name == "Review" %}
                <a class="upvote" href="#" data-href="{% url 'vote_on_reviews' object.id 'up' %}">Like</a>
        {% elif object|get_class_name == "Album" %}
                <a class="upvote" href="#" data-href="{% url 'vote_on_albums' object.id 'up' %}">Like</a>
        {% elif object|get_class_name == "Image" %}
                <a class="upvote" href="#" data-href="{% url 'vote_on_images' object.id 'up' %}">Like</a>
        {% elif object|get_class_name == "ThreadedComment" %}
                <a  class="upvote" href="#" data-href="{% url 'vote_on_comments' object.id 'up' %}">Like</a>
        {% elif object|get_class_name == "GenericWish" %}
                <a class="upvote" href="#" data-href="{% url 'vote_on_post' object.id 'up' %}">Like</a>
        {% elif object|get_class_name == "BroadcastWish" %}
                <a class="upvote" href="#" data-href="{% url 'vote_on_wish' object.id 'up' %}">Like</a>   
        {% elif object|get_class_name == "BroadcastDeal" %}
                <a class="upvote" href="#" data-href="{% url 'vote_on_deal' object.id 'up' %}">Like</a>       
        {% endif %}

    {% else %}
        {% if object|get_class_name == "Review" %}
                <a class="clearvote" href="#" data-href="{% url 'vote_on_reviews' object.id 'clear' %}">Unlike</a>
        {% elif object|get_class_name == "Album" %}
                <a  class="clearvote" href="#" data-href="{% url 'vote_on_albums' object.id 'clear' %}">Unlike</a>
        {% elif object|get_class_name == "Image" %}
                <a  class="clearvote" href="#" data-href="{% url 'vote_on_images' object.id 'clear' %}">Unlike</a>
        {% elif object|get_class_name == "ThreadedComment" %}
                <a  class="clearvote" href="#" data-href="{% url 'vote_on_comments' object.id 'clear' %}">Unlike</a>
        {% elif object|get_class_name == "GenericWish" %}
                <a  class="clearvote" href="#" data-href="{% url 'vote_on_post' object.id 'clear' %}">Unlike</a> 
        {% elif object|get_class_name == "BroadcastWish" %}
                <a  class="clearvote" href="#" data-href="{% url 'vote_on_wish' object.id 'clear' %}">Unlike</a>
        {% elif object|get_class_name == "BroadcastDeal" %}
                <a  class="clearvote" href="#" data-href="{% url 'vote_on_post' object.id 'clear' %}">Unlike</a>     
        {% endif %}
    {% endif %}
     <span class="cover-stat cover-stat-appreciations">
            <span class="stat-label be-font-inline">F</span>
            <a class="pScore" href="{{ voters }}">{{score.num_up_votes}}</a>
     </span>    
     
     </span>
{% endif %}

imagestore/templates/imagestore/tag.html
{% extends "imagestore/base.html" %}

{% load i18n %}
{% load thumbnail %}

{% block title %}
    {% trans "Gallery" %} - {% trans "Tag" %}: {{ tag }}
{% endblock %}

{% block imagestore-breadcrumb %}
    <li>{% trans "Tag" %}: {{ tag }}</li>
{% endblock %}

{% block content %}
    <h1>{% trans "Tag" %} - {{ tag }}</h1>
    {% include "imagestore/image-list.html" %}
{% endblock content %}

{% block content-related %}
    {% include "imagestore/tag-cloud.html" %}
{% endblock %}